### PR TITLE
FIX: Replace sensiolabs/security-checker with signify-nz/composer-security-checker

### LINKED ISSUE #57: Module no longer works, sensiolabs/security-checker is abandoned
We need to start hosting our own security checking tool, or add the ability to run this with a local CLI tool - see https://github.com/sensiolabs/security-checker

### PR DESCRIPTION
**Pull request by GuySartorelli**
Fixes #57

### CODE REVIEW

**Comment by ChloeSartorelli** [comment]
Scrutinizer failed because the composer1 cache hasn't got the new package yet (though why scrutinizer is using composer1 I couldn't tell you). Should be visible to composer1 in a day or so.

**Comment by ChloeSartorelli** [comment]
Scrutinizer failed this time because it's trying to use PHP 5.6... someone with access and appropriate know-how will need to update the configuration for this package's scrutinizer run.

**Review by maxime-rainville — CHANGES_REQUESTED** [review]
It's a good idea, but I'm thinking it might make more sense to use the [Packagist security advisory API](https://packagist.org/api/security-advisories/?packages[]=monolog/monolog) instead. I'm thinking that's probably going to more reliable in the long term.

**Comment by ChloeSartorelli** [comment]
Closing this as it's not an accepted approach.
Some cool Guy has [created a PR in composer/composer](https://github.com/composer/composer/pull/10798) which will add a PHP API for consuming the packagist security advisory API, so when that's merged I'll create a new PR that leverages it.

**Pull request closed without merging**
